image: gitpod/workspace-full

# Окружение: sqlite вместо Postgres, без Redis
env:
  DATABASE_URL: "sqlite+aiosqlite:///workspace/db.sqlite"
  SOLANA_RPC_URL: "https://api.mainnet-beta.solana.com"
  JWT_SECRET: "UltraSecureJWTSecretKey123!"
  ADMIN_USER: "admin"
  ADMIN_PASSWORD: "SuperSecretAdmin123"
  MM_SECRET_KEY: "any-string-you-like"

tasks:
  - name: backend
    init: |
      cd backend
      python3 -m venv .venv
      source .venv/bin/activate
      pip install --upgrade pip setuptools
      pip install --no-cache-dir -r requirements.txt
    command: |
      cd backend
      source .venv/bin/activate
      uvicorn app.main:app --host 0.0.0.0 --port 8000

  - name: frontend
    init: |
      cd frontend
      npm install
    command: |
      cd frontend
      npm run dev

ports:
  - port: 8000
    onOpen: open-preview
  - port: 3000
    onOpen: open-preview
