version: "3.8"
services:
  backend:
    build: ./backend
    env_file: .env
    ports:
      - "8000:8000"
    depends_on: [db, redis]
    restart: always

  frontend:
    build: ./frontend
    env_file: .env
    ports:
      - "3000:3000"
    restart: always

  db:
    image: postgres:15
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - db_data:/var/lib/postgresql/data
    restart: always

  redis:
    image: redis:7-alpine
    restart: always

  nginx:
    image: nginx:stable
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.dev.conf:/etc/nginx/nginx.conf:ro
    depends_on: [frontend, backend]
    restart: always

volumes:
  db_data:
